### ISSUE TITLE
Some indication message's data object confused.

### ISSUE THREAD

**Issue by PeterEB** [freebirdjs/freebird#2]
1. The message's data object of the indication `permitJoining` is missing the key `timeLeft`.
2. The property `auxId` of the indication `gadIncoming` message's data object not find in [freebird-web-client-server-spec](https://github.com/simenkid/freebird-web-client-server-spec/blob/master/spec.md#gadInfoObj).
3. The property `raw` of the indication `bannedDevIncoming` message's data object not find in [freebird-web-client-server-spec](https://github.com/simenkid/freebird-web-client-server-spec/blob/master/spec.md#IndicationData).

**Comment by simenkid** [comment]
(1) attach `timeLeft` key it permitJoin message
(2) add `auxId` for gadIncoming message in spec.
(3) kill `raw` key for bannedDevIncoming indication in ws message
