### ISSUE TITLE
Some wsApi confused.

### ISSUE THREAD

**Issue by PeterEB** [freebirdjs/freebird#4]
1. The API `enable()` and `disable()` exist in `fb._wsApis.dev`, but not find in [freebird-web-client-server-spec](https://github.com/simenkid/freebird-web-client-server-spec/blob/master/spec.md#RequestData).
2. The API `getProps()` and `setProps()` exist in [freebird-web-client-server-spec](https://github.com/simenkid/freebird-web-client-server-spec/blob/master/spec.md#RequestData), but not find in `fb._wsApis.dev` and `fb._wsApis.net`.

**Comment by simenkid** [comment]
(1) fix, add enable(), disable() for 'dev' and 'gad' in spec.
(2) add getProps() and setProp() APIs within 'dev' and 'gad' namespace.
